/**
 * Temas teológicos e séries de três dias. Mesmos critérios de escrita de
 * `devocionais.dados.ts`.
 */
import type { Devocional } from "./devocionais";

export const NOVOS: Devocional[] = [
  {
    id: "trindade",
    titulo: "Um só Deus, três pessoas",
    chamada: "Três dias diante do mistério da Trindade",
    descricao:
      "A palavra Trindade não aparece na Bíblia, mas o Pai, o Filho e o Espírito aparecem juntos, falando e agindo, do batismo de Jesus à bênção que fecha uma carta de Paulo. Três dias para olhar o mistério sem querer resolvê-lo, e descobrir que no centro de tudo existe amor.",
    categoria: "teologia",
    capa: { slug: "mt", capitulo: 3 },
    cor: "#7b8fd4",
    selo: "Novo",
    dias: [
      {
        titulo: "O céu se abre",
        leitura: { slug: "mt", capitulo: 3, de: 13, ate: 17 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "O amor antes do mundo",
        leitura: { slug: "jo", capitulo: 17, de: 20, ate: 26 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A graça, o amor e a comunhão",
        leitura: { slug: "2co", capitulo: 13, de: 11, ate: 14 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "graca",
    titulo: "Graça que justifica",
    chamada: "Três dias sobre ser aceito sem merecer",
    descricao:
      "Graça é a palavra mais bonita do vocabulário cristão, e a mais fácil de esvaziar. Três dias com os textos em que Paulo explica o que Deus fez por quem não podia se salvar sozinho, e o que isso muda numa vida que vive tentando provar que merece.",
    categoria: "teologia",
    capa: { slug: "rm", capitulo: 5 },
    cor: "#d4a35b",
    selo: "Novo",
    dias: [
      {
        titulo: "Todos pecaram, todos podem ser justificados",
        leitura: { slug: "rm", capitulo: 3, de: 21, ate: 26 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Ainda fracos, ainda pecadores",
        leitura: { slug: "rm", capitulo: 5, de: 6, ate: 11 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Não por obras de justiça",
        leitura: { slug: "tt", capitulo: 3, de: 3, ate: 7 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "encarnacao",
    titulo: "Deus se fez gente",
    chamada: "Três dias sobre a encarnação",
    descricao:
      "O cristianismo faz uma afirmação escandalosa: o Deus que criou tudo entrou na criação, com corpo, fome e cansaço. Três dias para pensar no que significa Jesus ser Deus e homem, e por que isso não é detalhe de catecismo, mas o chão da nossa esperança.",
    categoria: "teologia",
    capa: { slug: "jo", capitulo: 1 },
    cor: "#c98a6b",
    selo: "Novo",
    dias: [
      {
        titulo: "A imagem do Deus invisível",
        leitura: { slug: "cl", capitulo: 1, de: 15, ate: 20 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "O que as nossas mãos tocaram",
        leitura: { slug: "1jo", capitulo: 1, de: 1, ate: 4 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Semelhante aos irmãos",
        leitura: { slug: "hb", capitulo: 2, de: 14, ate: 18 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "alianca",
    titulo: "O Deus da aliança",
    chamada: "Três dias sobre o Deus que se compromete",
    descricao:
      "A Bíblia inteira pode ser lida como a história de um Deus que faz promessas e as cumpre: com Noé, com Abraão, com Israel e, por fim, numa aliança nova no sangue de Jesus. Três dias para entender a palavra que amarra o Antigo e o Novo Testamento.",
    categoria: "teologia",
    capa: { slug: "gn", capitulo: 9 },
    cor: "#8a9a5b",
    selo: "Novo",
    dias: [
      {
        titulo: "O arco nas nuvens",
        leitura: { slug: "gn", capitulo: 9, de: 8, ate: 17 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Uma aliança nova",
        leitura: { slug: "jr", capitulo: 31, de: 31, ate: 34 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "O cálice da nova aliança",
        leitura: { slug: "lc", capitulo: 22, de: 14, ate: 20 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "espirito-santo-imagens",
    titulo: "Sopro, vento e fogo",
    chamada: "Cinco imagens bíblicas do Espírito Santo",
    descricao:
      "A Bíblia quase nunca define o Espírito Santo; ela o mostra por imagens. O sopro que paira sobre as águas, o vento que dá vida a ossos secos, o vento que ninguém controla, a água que mata a sede, a liberdade que transforma. Cinco dias para conhecer quem age em nós por dentro.",
    categoria: "teologia",
    capa: { slug: "ez", capitulo: 37 },
    cor: "#e07a3f",
    selo: "Novo",
    dias: [
      {
        titulo: "Pairando sobre as águas",
        leitura: { slug: "gn", capitulo: 1, de: 1, ate: 2 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Sopro sobre ossos secos",
        leitura: { slug: "ez", capitulo: 37, de: 1, ate: 10 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "O vento sopra onde quer",
        leitura: { slug: "jo", capitulo: 3, de: 5, ate: 8 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Rios de água viva",
        leitura: { slug: "jo", capitulo: 7, de: 37, ate: 39 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Onde está o Espírito, há liberdade",
        leitura: { slug: "2co", capitulo: 3, de: 17, ate: 18 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "apocalipse",
    titulo: "Apocalipse sem medo",
    chamada: "Sete dias com o livro que termina em esperança",
    descricao:
      "Muita gente tem medo do Apocalipse, ou só o lê para adivinhar o futuro. Mas ele foi escrito para consolar igrejas pequenas e perseguidas: no centro do livro não está a besta, está um Cordeiro no trono. Sete dias com as cenas que mais falam ao coração, sem tabela de datas.",
    categoria: "teologia",
    capa: { slug: "ap", capitulo: 1 },
    cor: "#5b6fb3",
    selo: "Novo",
    dias: [
      {
        titulo: "Alguém semelhante a filho de homem",
        leitura: { slug: "ap", capitulo: 1, de: 9, ate: 18 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "O primeiro amor",
        leitura: { slug: "ap", capitulo: 2, de: 1, ate: 7 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Nem frio nem quente",
        leitura: { slug: "ap", capitulo: 3, de: 14, ate: 22 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Digno é o Cordeiro",
        leitura: { slug: "ap", capitulo: 5, de: 1, ate: 14 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Uma multidão que ninguém podia contar",
        leitura: { slug: "ap", capitulo: 7, de: 9, ate: 17 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Venceram pelo sangue do Cordeiro",
        leitura: { slug: "ap", capitulo: 12, de: 7, ate: 12 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "O rio da água da vida",
        leitura: { slug: "ap", capitulo: 22, de: 1, ate: 5 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "coracao-inteiro",
    titulo: "Coração inteiro",
    chamada: "Três dias para a fé num mundo de notificações",
    descricao:
      "A gente vive com a atenção picada em mil pedaços. A Bíblia não fala de celular, mas fala muito de um coração dividido e de onde colocamos os olhos. Três dias curtos para reaprender a estar inteiro diante de Deus.",
    categoria: "vida-com-deus",
    capa: { slug: "mc", capitulo: 1 },
    cor: "#4fa3a0",
    selo: "Novo",
    dias: [
      {
        titulo: "Une o meu coração",
        leitura: { slug: "sl", capitulo: 86, de: 10, ate: 13 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "De madrugada, a sós",
        leitura: { slug: "mc", capitulo: 1, de: 35, ate: 39 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Tudo o que é verdadeiro",
        leitura: { slug: "fp", capitulo: 4, de: 8, ate: 9 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "enquanto-espero",
    titulo: "Enquanto espero",
    chamada: "Três dias para quem está na sala de espera",
    descricao:
      "Esperar resposta de exame, de emprego, de reconciliação, de oração. A espera cansa mais do que muita luta. Três dias com textos de gente que esperou em Deus sem saber quando nem como a resposta viria.",
    categoria: "coracao",
    capa: { slug: "hc", capitulo: 2 },
    cor: "#9b7fc4",
    selo: "Novo",
    dias: [
      {
        titulo: "Espera pelo Senhor",
        leitura: { slug: "sl", capitulo: 27, de: 13, ate: 14 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Bom é aguardar em silêncio",
        leitura: { slug: "lm", capitulo: 3, de: 21, ate: 26 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Ainda que tarde, espera",
        leitura: { slug: "hc", capitulo: 2, de: 1, ate: 3 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "palavras-que-curam",
    titulo: "Palavras que curam",
    chamada: "Três dias sobre o que sai da nossa boca",
    descricao:
      "Uma frase pode carregar alguém por anos, para o bem ou para o mal. Jesus diz que a boca fala do que o coração está cheio. Três dias sobre falar com verdade, graça e sal.",
    categoria: "carater",
    capa: { slug: "mt", capitulo: 12 },
    cor: "#c4655b",
    selo: "Novo",
    dias: [
      {
        titulo: "Da abundância do coração",
        leitura: { slug: "mt", capitulo: 12, de: 33, ate: 37 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Morte e vida no poder da língua",
        leitura: { slug: "pv", capitulo: 18, de: 20, ate: 21 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Temperada com sal",
        leitura: { slug: "cl", capitulo: 4, de: 5, ate: 6 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "sem-comparacao",
    titulo: "Sem comparação",
    chamada: "Três dias para sair da corrida com os outros",
    descricao:
      "A comparação rouba a alegria e a gratidão, e as redes sociais só aumentam a vitrine. Três dias com um salmista que quase escorregou de inveja, um discípulo que quis saber do outro, e um corpo em que nenhum membro é o mais importante.",
    categoria: "coracao",
    capa: { slug: "sl", capitulo: 73 },
    cor: "#6b9bc4",
    selo: "Novo",
    dias: [
      {
        titulo: "Quase me resvalaram os pés",
        leitura: { slug: "sl", capitulo: 73, de: 1, ate: 17 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Que te importa?",
        leitura: { slug: "jo", capitulo: 21, de: 20, ate: 23 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Cada um, uma parte do corpo",
        leitura: { slug: "1co", capitulo: 12, de: 14, ate: 26 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "na-encruzilhada",
    titulo: "Na encruzilhada",
    chamada: "Três dias sobre decidir com Deus",
    descricao:
      "Mudar de emprego, de cidade, de relacionamento, de curso. Quem quer fazer a vontade de Deus muitas vezes trava com medo de errar. Três dias com textos que não dão uma fórmula, mas mostram um Deus que guia quem está a caminho.",
    categoria: "carater",
    capa: { slug: "at", capitulo: 16 },
    cor: "#b38f4f",
    selo: "Novo",
    dias: [
      {
        titulo: "Portas fechadas, uma visão de noite",
        leitura: { slug: "at", capitulo: 16, de: 6, ate: 10 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Instruir-te-ei",
        leitura: { slug: "sl", capitulo: 32, de: 8, ate: 9 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Este é o caminho",
        leitura: { slug: "is", capitulo: 30, de: 19, ate: 21 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "fora-do-esconderijo",
    titulo: "Fora do esconderijo",
    chamada: "Três dias sobre a vergonha e o olhar de Deus",
    descricao:
      "A culpa diz: eu fiz algo errado. A vergonha diz: eu sou errado. Desde o jardim, a gente se esconde. Três dias com um Deus que vai atrás de quem se escondeu, põe à mesa quem se achava um cão morto e promete que quem confia nele não será envergonhado.",
    categoria: "coracao",
    capa: { slug: "gn", capitulo: 3 },
    cor: "#a3687a",
    selo: "Novo",
    dias: [
      {
        titulo: "Onde estás?",
        leitura: { slug: "gn", capitulo: 3, de: 8, ate: 21 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "À mesa do rei",
        leitura: { slug: "2sm", capitulo: 9, de: 1, ate: 13 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "Não te envergonharás",
        leitura: { slug: "is", capitulo: 54, de: 4, ate: 8 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
];
