/**
 * Mais jornadas de um mês: a Bíblia inteira em panorama, um evangelho
 * inteiro e trinta salmos. Mesmos critérios de `devocionais.dados.ts`.
 */
import type { Devocional } from "./devocionais";

export const JORNADAS: Devocional[] = [
  {
    id: "a-grande-historia",
    titulo: "A grande história",
    chamada: "A Bíblia inteira, de Gênesis a Apocalipse, em 30 dias",
    descricao:
      "A Bíblia são 66 livros, mas uma história só: criação, queda, promessa, povo, rei, exílio, Messias, cruz, ressurreição, igreja e todas as coisas novas. Em 30 dias, um texto-chave de cada grande momento, para enxergar o fio que costura tudo e o lugar da sua vida nele.",
    categoria: "jornada",
    capa: { slug: "gn", capitulo: 28 },
    cor: "#3f8fc4",
    selo: "Um mês",
    dias: [
      {
        titulo: "A definir 1",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 2",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 3",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 4",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 5",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 6",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 7",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 8",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 9",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 10",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 11",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 12",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 13",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 14",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 15",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 16",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 17",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 18",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 19",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 20",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 21",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 22",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 23",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 24",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 25",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 26",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 27",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 28",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 29",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 30",
        leitura: { slug: "gn", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "marcos-em-30-dias",
    titulo: "Marcos em 30 dias",
    chamada: "Um evangelho inteiro, do começo ao fim, em um mês",
    descricao:
      "Marcos é o evangelho mais curto e mais rápido: a palavra \"logo\" aparece o tempo todo. Em 30 dias você lê o livro inteiro, uma cena por vez, e caminha com Jesus da Galileia até o túmulo vazio, com a pergunta que atravessa tudo: quem é este?",
    categoria: "jornada",
    capa: { slug: "mc", capitulo: 4 },
    cor: "#c46b3f",
    selo: "Um mês",
    dias: [
      {
        titulo: "A definir 1",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 2",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 3",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 4",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 5",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 6",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 7",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 8",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 9",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 10",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 11",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 12",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 13",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 14",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 15",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 16",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 17",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 18",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 19",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 20",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 21",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 22",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 23",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 24",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 25",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 26",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 27",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 28",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 29",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 30",
        leitura: { slug: "mc", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
  {
    id: "salmos-30-oracoes",
    titulo: "Salmos: 30 orações",
    chamada: "Um salmo por dia, para aprender a orar com a Bíblia",
    descricao:
      "Os Salmos são o livro de orações que Jesus rezou. Tem louvor, queixa, medo, alegria, culpa, saudade e confiança. Em 30 dias, 30 salmos diferentes, para descobrir que existe palavra para todo estado da alma, e que todos eles podem ser levados a Deus.",
    categoria: "jornada",
    capa: { slug: "sl", capitulo: 19 },
    cor: "#6bb38a",
    selo: "Um mês",
    dias: [
      {
        titulo: "A definir 1",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 2",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 3",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 4",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 5",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 6",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 7",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 8",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 9",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 10",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 11",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 12",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 13",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 14",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 15",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 16",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 17",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 18",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 19",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 20",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 21",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 22",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 23",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 24",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 25",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 26",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 27",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 28",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 29",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
      {
        titulo: "A definir 30",
        leitura: { slug: "sl", capitulo: 1, de: 1 },
        reflexao: ["A definir."],
        pergunta: "A definir.",
        oracao: "A definir.",
        pratica: "A definir.",
      },
    ],
  },
];
